version: '3.8'

services:
  invoice-service:
    build:
      context: ./invoice-service
      dockerfile: Dockerfile
    container_name: invoice-service
    ports:
      - '3000:3000'
    environment:
      - MONGO_URL=${MONGO_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
    depends_on:
      - mongo
      - rabbitmq
    restart: unless-stopped
    networks:
      - app_network

  email-sender:
    build:
      context: ./email-sender
      dockerfile: Dockerfile
    container_name: email-sender
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
    depends_on:
      - rabbitmq
    restart: unless-stopped
    networks:
      - app_network

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'mongo', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

volumes:
  mongodb_data:

networks:
  app_network:
