version: '3.8'

services:
  invoice-service:
    build:
      context: .
      dockerfile: ./src/invoices/Dockerfile
    container_name: invoice-service
    ports:
      - '3000:3000'
    environment:
      - MONGO_URL=mongodb://mongo:27017/invoice_service
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - mongo
      - rabbitmq
    restart: always

  daily-summary:
    build:
      context: .
      dockerfile: ./src/daily-summary/Dockerfile
    container_name: daily-summary
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq
    restart: always

  email:
    build:
      context: .
      dockerfile: ./src/email/Dockerfile
    container_name: email
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq
    restart: always

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data:
